services:
  postgres:
    image: postgres:17
    container_name: tkww_postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "{{ env_var('DBT_USER') }}"
      POSTGRES_PASSWORD: "{{ env_var('DBT_USER') }}"
      POSTGRES_DB: tkww_product

  python:
    image: python:3.13
    container_name: tkww_python
    volumes:
      - ../:/app
    working_dir: /app
    command: sh -c "pip install -r python/requirements.txt && tail -f /dev/null"

volumes:
  pgdata: